### ISSUE TITLE
LocalBroadcastManager is deprecated, should not be used in MainActivity.kt

### ISSUE THREAD

**Issue by javalc6** [android/camera-samples#206]
The CameraX sample is using a deprecated class in MainActivity.kt (onKeyDown):  [LocalBroadcastManager](https://developer.android.com/reference/androidx/localbroadcastmanager/content/LocalBroadcastManager?hl=en)
Please clean-up the code by using not-deprecated classes
Thank you.

**Comment by owahltinez** [comment]
LocalBroadcastManager appears to have been deprecated since Android R, I believe, which is only in developer preview state so far.

It is a much simpler solution than implementing a ViewModel, an application-level event bus seems appropriate for hardware button event broadcasting in the single activity pattern.

We can reconsider a different option once ViewModel-related AndroidX libraries are in a more mature state.
