### ISSUE TITLE
CameraX happens random focus distances and looks blurry

### ISSUE THREAD

**Issue by apcx** [android/camera-samples#213]
I clone the [ CameraXBasic ] project, and just run it on my [ HUAWEI mate 30 5G ].

Usually it's fine, but sometimes the preview appears to be extremely near my face and looks blurry.

It seems that every time I shutdown and relaunch the app, cameraX randomly measures a focus distance, which can be VERY FAR or VERY NEAR.

Gradle dependencies:
    def camera_version = '1.0.0-beta03'
    implementation "androidx.camera:camera-camera2:$camera_version"
    implementation "androidx.camera:camera-lifecycle:$camera_version"
    implementation 'androidx.camera:camera-view:1.0.0-alpha10'

**Comment by owahltinez** [comment]
Thanks for reporting, this sounds like an issue with the underlying CameraX library. Please open a bug in the [library issue tracker](https://issuetracker.google.com).

If you start a thread at the [developer forums](https://g.co/camerax/developers), the team may be able to help you find a workaround until the issue is fixed.
