### ISSUE TITLE
CameraXBasic Front Camera == Nightvision

### ISSUE THREAD

**Issue by tlorens** [android/camera-samples#239]
When switching to the front facing camera.  I'm illuminated by some IR light coming from the upper right corner of my Pixel 4.  I can put my thumb over it and my face dims.  The picture is B&W, grainy and looks like nightvision.   First time tinkering with the camera on Android so I'm not sure where to look nor how to fix it.

**Comment by owahltinez** [comment]
Thanks for submitting this, @tlorens. You are not doing anything wrong, this is a known issue happening in the Pixel 4. CameraX is mistakenly picking the IR camera rather than the RGB one. It doesn't even happen every time! There is a fix for it, and I think it will be available in `beta04` version of CameraX library.

I'm closing this out because it's a library issue, not a sample issue. But feel free to reopen if you think that's wrong.
