### ISSUE TITLE
[CameraX] App crashes api < 21

### ISSUE THREAD

**Issue by sawyerhard** [android/camera-samples#92]
- Android version 4.4.4, API 19
- dependencies:
androidx.camera:camera-core:1.0.0-alpha06
androidx.camera:camera-camera2:1.0.0-alpha06

**Problem**
I'm trying to use this library only for API > 21, but i also can't run my application for API < 21 . 
I want to use this library like this: 

```
if (Build.VERSION.SDK_INT < Build.VERSION_CODES.LOLLIPOP) {
            useOldCamera();
        } else {
            useCameraX();
        }
```
When i run my application, i get crash with this exception:
`E/UncaughtException: java.lang.NoClassDefFoundError: android.util.Size`

I'm trying to use this method, but it's not help: [stackoverflow](https://stackoverflow.com/questions/56374939/android-application-with-camera2-library-crash-on-start-for-sdk19)

**Comment by Merseyside** [comment]
The same issue

**Comment by youlovejohnny** [comment]
Same, fix it asap please

**Comment by roffel** [comment]
I would like to be able to build with minSDK 16 as well. It is fine if I need to fall back to an own camera implementation for Android 4.x devices.

**Comment by waliahimanshu** [comment]
Camer2 and CameraX api's minimum supported API level is 21.

**Comment by owahltinez** [comment]
As @waliahimanshu CameraX is built on Camera2, and Camera2 only supports API 21+

**Comment by sawyerhard** [comment]
but why did you do so? why i cant use overrideLibrary tools in manifest?

**Comment by roffel** [comment]
@owahltinez But before I could write an if statement stating `if < api 21 use the deprecated camera` so I could still build for Android 4.x. That is not possible anymore.

**Comment by peterdk** [comment]
Here another vote, I want to use CameraX where possible, but write the code for legacy Camera myself, with a condition SDK_INT check. Now just adding the implementations makes the app crash. I need to support 4.1+, so I really don't understand why it cannot be used conditionally.
```
implementation 'androidx.camera:camera-core:1.0.0-alpha06'
implementation 'androidx.camera:camera-camera2:1.0.0-alpha06'
```

**Comment by waliahimanshu** [comment]
@peterdk The crash is due to fact that the cameraX using `size` class called from  the `Camera2Initializer` content provider which is added in api 21.

One way to get around that to create a empty content provider with the same name `Camera2Initializer`
`class Camera2Initializer : ContentProvider() {...}`  

Init the library before starting the camera 
`CameraX.init(applicationContext, Camera2AppConfig.create(applicationContext))`

Having said that, the init process has changes significantly in alpha-07.

You can use this workaround, until you decide to bump the min-sdk version.
